# Generated by Django 2.0.5 on 2018-06-23 23:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('province', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=25)),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('date_account_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_details', models.CharField(max_length=10000)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Customers')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('color', models.CharField(max_length=250)),
                ('size', models.CharField(max_length=10)),
                ('product_description', models.CharField(max_length=600)),
                ('product_image_1', models.ImageField(blank=True, upload_to='products')),
                ('product_image_2', models.ImageField(blank=True, upload_to='products')),
                ('product_image_3', models.ImageField(blank=True, upload_to='products')),
                ('product_image_4', models.ImageField(blank=True, upload_to='products')),
            ],
        ),
        migrations.CreateModel(
            name='Ref_Order_Status_Codes',
            fields=[
                ('order_status_code', models.AutoField(primary_key=True, serialize=False)),
                ('order_status_description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ref_Product_type',
            fields=[
                ('product_type_code', models.AutoField(primary_key=True, serialize=False)),
                ('product_type_description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_type_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Ref_Product_type'),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_status_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Ref_Order_Status_Codes'),
        ),
        migrations.AddField(
            model_name='address',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Customers'),
        ),
    ]
