# Generated by Django 2.0.5 on 2018-06-24 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_customer_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='last_login',
        ),
    ]
