# Generated by Django 2.0.5 on 2018-06-24 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20180624_1805'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ref_Order_Status_Codes',
            new_name='Ref_Order_Status_Code',
        ),
    ]
