# Generated by Django 2.0.5 on 2018-06-26 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20180624_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image_1',
            field=models.ImageField(blank=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image_2',
            field=models.ImageField(blank=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image_3',
            field=models.ImageField(blank=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image_4',
            field=models.ImageField(blank=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type_code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.Ref_Product_type'),
        ),
    ]
